services:
  # etcd for APISIX configuration storage
  etcd:
    image: bitnami/etcd:3.5.17
    container_name: etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ports:
      - "2379:2379"

  # APISIX instance
  apisix:
    image: apache/apisix:3.11.0-debian
    container_name: apisix
    restart: always
    depends_on:
      - etcd
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"
      - "9443:9443"
      # - "9091:9091" # APISIX Admin API port (default is 9091)

  # APISIX Dashboard
  apisix-dashboard:
    image: apache/apisix-dashboard
    container_name: apisix-dashboard
    restart: always
    depends_on:
      - apisix
      - etcd
    volumes:
      - ./dashboard_conf/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - ./apisix-dashboard-logs:/usr/local/apisix-dashboard/logs
    ports:
      - "9000:9000"