apisix:
  node_listen: 9080          # APISIX listening port for HTTP
  plugins:
    - jwt-auth
  
deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
  etcd:
    host:
      - http://etcd:2379
    prefix: "/apisix"
    timeout: 30